id: I0363A2A8
default_language: zh
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-10 00:18:00.616207
last_modified: 2023-02-10 00:18:00.616357
source_metadata:
  title: 'MSV 6,09: Māṇavikā'
  language: zh
bases:
  0E48:
    base_file: 0E48.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
